### ISSUE TITLE
Port over IEnumerable testing extension methods

### ISSUE THREAD

**Issue by mrjones2014** [AndcultureCode/AndcultureCode.CSharp.Testing#24]
As part of a client project, we've added some `IEnumerable<T>` extension methods that are pretty useful.
- `ShouldBeOfSize<T>(this IEnumerable<T> collection, int size)`
- `ShouldBeOrderedBy<T, V>(this IEnumerable<T> items, Func<T, V> keySelector) where V : IComparable<V>`
- `ShouldBeOrderedByDescending<T, V>(this IEnumerable<T> items, Func<T, V> keySelector) where V : IComparable<V>`

**Comment by brandongregoryscott** [comment]
Oh, beat me to it! Awesome 👏 Please take note of my feedback on that CR & name the file/static class appropriately

**Comment by mrjones2014** [comment]
@brandongregoryscott yep, this project already has an `IEnumerableExtensions`, I was gonna put them in there.

**Comment by brandongregoryscott** [comment]
Published with [v0.5.0](https://github.com/AndcultureCode/AndcultureCode.CSharp.Testing/releases/tag/v0.5.0)
