### ISSUE TITLE
IResult Auditable matcher extensions

### ISSUE THREAD

**Issue by brandongregoryscott** [AndcultureCode/AndcultureCode.CSharp.Testing#48]
Recently found myself writing some assertions on `IResult`s of `IAuditable` models... for example, verifying all of the records returned by a controller belong to the expected user, or a record is deleted, etc.

`AuditableDto` and other common dtos are slated for extraction to [AndcultureCode.CSharp.Web](https://github.com/AndcultureCode/AndcultureCode.CSharp.Web) in this boilerplate issue: https://github.com/AndcultureCode/AndcultureCode.DotnetReact.Boilerplate/issues/11. 

For the sake of not bringing along the web project into this testing project, I am proposing we update those dtos to inherit from their respective model interfaces (`IEntity`, `IAuditable`, etc.)

Proposed API (feel free to add on/revise as fit):
```cs
public static void ShouldBeCreated<TAuditable>(this IResult<TAuditable> result) where TAuditable : IAuditable
public static void ShouldBeCreatedBy<TAuditable>(this IResult<TAuditable> result, long? createdById) where TAuditable : IAuditable
public static void ShouldBeCreatedBy<TAuditable>(this IResult<TAuditable> result, IEntity createdBy) where TAuditable : IAuditable
public static void ShouldBeDeleted<TAuditable>(this IResult<TAuditable> result) where TAuditable : IAuditable
public static void ShouldBeDeletedBy<TAuditable>(this IResult<TAuditable> result, long? deletedById) where TAuditable : IAuditable
public static void ShouldBeDeletedBy<TAuditable>(this IResult<TAuditable> result, IEntity deletedBy) where TAuditable : IAuditable
public static void ShouldBeUpdated<TAuditable>(this IResult<TAuditable> result) where TAuditable : IAuditable
public static void ShouldBeUpdatedBy<TAuditable>(this IResult<TAuditable> result, long? updatedById) where TAuditable : IAuditable
public static void ShouldBeUpdatedBy<TAuditable>(this IResult<TAuditable> result, IEntity updatedBy) where TAuditable : IAuditable
```

**Comment by wintondeshong** [comment]
@brandongregoryscott dig the proposed API for new assertions! I vote going the route of inheriting from 'IEntity, IAuditable, etc.'. Those specific data transfer objects are out in presentation for the purposes of use of API (presentational). Creating an interface to represent them in core could start to break the onion.

**Comment by brandongregoryscott** [comment]
Awesome - I can get behind that 👍 I'll update this issue as well as the boilerplate issue to include this
