### ISSUE TITLE
Add IResultMatcherExtension for ShouldHaveBasicErrorKey

### ISSUE THREAD

**Issue by dylanjustice** [AndcultureCode/AndcultureCode.CSharp.Testing#6]
Port `ShouldHaveBasicError` extension method for `IResult<T>` to collapse 
```csharp
result.ShouldHaveBasicErrors();
result.ShouldHaveErrorsFor(ErrorConstants.BASIC_ERROR_KEY)
```

**Comment by brandongregoryscott** [comment]
Released in [v0.2.2](https://github.com/AndcultureCode/AndcultureCode.CSharp.Testing/releases/tag/v0.2.2)
